CREATE OR REPLACE PROCEDURE drop_tables AS
BEGIN 
    EXECUTE IMMEDIATE 'DROP TABLE FOTO';
    EXECUTE IMMEDIATE 'DROP TABLE SEGURO';
    EXECUTE IMMEDIATE 'DROP TABLE BONUS';
    EXECUTE IMMEDIATE 'DROP TABLE ADQUIERE';
    EXECUTE IMMEDIATE 'DROP TABLE ENTRADA';
    EXECUTE IMMEDIATE 'DROP TABLE PAGO';
    EXECUTE IMMEDIATE 'DROP TABLE COMENTARIO';
    EXECUTE IMMEDIATE 'DROP TABLE PARTICIPAEN';
    EXECUTE IMMEDIATE 'DROP TABLE USUARIO';
    EXECUTE IMMEDIATE 'DROP TABLE INCIDENCIA';
    EXECUTE IMMEDIATE 'DROP TABLE GRUPO';
    EXECUTE IMMEDIATE 'DROP TABLE TOUR';
    EXECUTE IMMEDIATE 'DROP TABLE GUIA';
END; 
/

CREATE OR REPLACE PROCEDURE inserta_foto (v_url IN FOTO.URL_FOTO%TYPE, v_id_tour IN FOTO.ID_TOUR%TYPE) AS
BEGIN 
    INSERT INTO FOTO (URL_FOTO,ID_TOUR) VALUES (v_url, v_id_tour);
END inserta_foto;
/

CREATE OR REPLACE PROCEDURE inserta_usuario(
   v_pass IN USUARIO.PASS_USER%TYPE,
   v_nombre IN USUARIO.NOMBRE%TYPE, 
   v_apellidos IN USUARIO.APELLIDOS%TYPE,
   v_dni IN USUARIO.DNI%TYPE, 
   v_telefono IN USUARIO.TELEFONO%TYPE, 
   v_email IN USUARIO.EMAIL%TYPE,
   v_fnac IN USUARIO.FECHA_NAC%TYPE) IS
BEGIN
    INSERT INTO USUARIO (PASS_USER, NOMBRE, APELLIDOS, DNI, TELEFONO, EMAIL, FECHA_NAC) VALUES (v_pass, v_nombre, v_apellidos, v_dni, v_telefono, v_email, v_fnac);
    COMMIT WORK;

END inserta_usuario; 
/

CREATE OR REPLACE PROCEDURE inserta_guia ( 
   v_pass IN GUIA.PASS_USER%TYPE,
   v_nombre IN GUIA.NOMBRE%TYPE,
   v_apell IN GUIA.APELLIDO%TYPE,
   v_dni IN GUIA.DNI%TYPE,
   v_email IN GUIA.EMAIL%TYPE, 
   v_acred IN GUIA.NUM_ACREDITACION%TYPE)  AS
BEGIN 
    INSERT INTO GUIA (PASS_USER, NOMBRE, APELLIDO, DNI, EMAIL, NUM_ACREDITACION)
    VALUES (v_pass, v_nombre, v_apell, v_dni, v_email, v_acred); 
    COMMIT WORK;
END inserta_guia; 
/

CREATE OR REPLACE PROCEDURE inserta_tour(
   v_idguia IN TOUR.ID_GUIA%TYPE,
   v_nombre IN TOUR.NOMBRE%TYPE,
   v_tour IN TOUR.TOUR%TYPE,
   v_dur IN TOUR.DURACION%TYPE,
   v_descr IN TOUR.DESCRIPCION%TYPE,
   v_cost IN TOUR.IMPORTE%TYPE,
   v_plazas IN TOUR.MAX_PLAZAS%TYPE) AS
BEGIN 
    INSERT INTO TOUR (ID_GUIA, NOMBRE, TOUR, DURACION, DESCRIPCION, IMPORTE, MAX_PLAZAS) VALUES (v_idguia, v_nombre, v_tour, v_dur, v_descr, v_cost, v_plazas);
    COMMIT WORK;

END inserta_tour; 
/

CREATE OR REPLACE PROCEDURE inserta_grupo(
   v_idtour IN GRUPO.ID_TOUR%TYPE,
   v_fecha IN GRUPO.FECHA%TYPE,
   v_hora IN GRUPO.HORA%TYPE) AS
BEGIN 
    INSERT INTO GRUPO (ID_TOUR, FECHA, HORA) VALUES (v_idtour, v_fecha, v_hora);
    COMMIT WORK;
END inserta_grupo; 
/

CREATE OR REPLACE PROCEDURE inserta_incidencia(
   v_idgr IN INCIDENCIA.ID_GRUPO%TYPE,
   v_text IN INCIDENCIA.TEXTO%TYPE,
   v_f IN INCIDENCIA.FECHA%TYPE,
   v_h IN INCIDENCIA.HORA%TYPE) AS
BEGIN 
    INSERT INTO INCIDENCIA (ID_GRUPO, TEXTO, FECHA, HORA) VALUES (v_idgr, v_text, v_f, v_h);
    COMMIT WORK;
END inserta_incidencia; 
/

CREATE OR REPLACE PROCEDURE inserta_participa_en (
   v_idus IN PARTICIPAEN.ID_USUARIO%TYPE,
   v_idgr IN PARTICIPAEN.ID_GRUPO%TYPE) AS
BEGIN 
    INSERT INTO PARTICIPAEN (ID_USUARIO, ID_GRUPO) VALUES (v_idus, v_idgr);
    COMMIT WORK;

END inserta_participa_en; 
/

CREATE OR REPLACE PROCEDURE inserta_comentario(
   v_text IN COMENTARIO.TEXTO%TYPE,
   v_idus IN COMENTARIO.ID_USUARIO%TYPE,
   v_idt IN COMENTARIO.ID_TOUR%TYPE) AS
BEGIN 
    INSERT INTO COMENTARIO (TEXTO,ID_USUARIO,ID_TOUR) VALUES (v_text, v_idus, v_idt);
    COMMIT WORK;
END inserta_comentario; 
/

CREATE OR REPLACE PROCEDURE inserta_pago(
   v_idus IN PAGO.ID_USUARIO%TYPE,
   v_fech IN PAGO.FECHA_PAGO%TYPE,
   v_imp IN PAGO.IMPORTE%TYPE) AS
BEGIN 
    INSERT INTO PAGO (ID_USUARIO,FECHA_PAGO,IMPORTE) VALUES (v_idus, v_fech, v_imp);
    COMMIT WORK;
END inserta_pago; 
/

CREATE OR REPLACE PROCEDURE inserta_entrada(
    v_idp IN ENTRADA.ID_PAGO%TYPE,
    v_imp IN ENTRADA.IMPORTE%TYPE,
    v_tpen IN ENTRADA.TIPO_ENTRADA%TYPE) AS
BEGIN 
    INSERT INTO ENTRADA (ID_PAGO,IMPORTE,TIPO_ENTRADA) VALUES (v_idp, v_imp, v_tpen);
    COMMIT WORK;
END; 
/

CREATE OR REPLACE PROCEDURE inserta_adquiere(
    v_idt IN ADQUIERE.ID_TOUR%TYPE,
    v_ide IN ADQUIERE.ID_ENTRADA%TYPE) AS
BEGIN 
    INSERT INTO ADQUIERE (ID_TOUR,ID_ENTRADA) VALUES (v_idt, v_ide);
    COMMIT WORK;
END; 
/

CREATE OR REPLACE PROCEDURE inserta_bonus(
   v_idp IN BONUS.ID_PAGO%TYPE,
   v_temp IN BONUS.TIPO_TEMPORADA%TYPE,
   v_imp IN BONUS.IMPORTE%TYPE) AS
BEGIN 
     INSERT INTO BONUS (ID_PAGO,TIPO_TEMPORADA,IMPORTE) VALUES (v_idp, v_temp, v_imp);
     COMMIT WORK;
END; 
/

CREATE OR REPLACE PROCEDURE inserta_seguro(
    v_imp IN SEGURO.IMPORTE%TYPE,
    v_idp IN SEGURO.ID_PAGO%TYPE,
    v_tip IN SEGURO.TIPO_SEGURO%TYPE) AS
BEGIN 
     INSERT INTO SEGURO (IMPORTE,ID_PAGO,TIPO_SEGURO) VALUES (v_imp, v_idp, v_tip);
    COMMIT WORK;
END; 
/

CREATE OR REPLACE PROCEDURE quitar_tour (
    v_idt IN TOUR.ID_TOUR%TYPE) AS
  NUM_GRUPOS NUMBER;
BEGIN
  SELECT COUNT(*) INTO NUM_GRUPOS FROM GRUPO WHERE GRUPO.ID_TOUR = v_idt;
  
  IF (NUM_GRUPOS <> 0) THEN
    RAISE_APPLICATION_ERROR(-20600,'No se puede quitar el tour porque tiene grupos asignados');
  ELSE
    DELETE FROM FOTO WHERE ID_TOUR = v_idt;
    DELETE FROM ADQUIERE WHERE ID_TOUR = v_idt;
    DELETE FROM COMENTARIO WHERE ID_TOUR = v_idt;
    DELETE FROM TOUR WHERE ID_TOUR = v_idt;
  END IF;
END;
/


CREATE OR REPLACE PROCEDURE modificar_tour(
    v_idt IN TOUR.ID_TOUR%TYPE,
    v_nombre IN TOUR.NOMBRE%TYPE,
    v_t IN TOUR.TOUR%TYPE,
    v_dur IN TOUR.DURACION%TYPE,
    v_desc IN TOUR.DESCRIPCION%TYPE,
    v_coste IN TOUR.IMPORTE%TYPE,
    v_max_plazas IN TOUR.MAX_PLAZAS%TYPE) IS
BEGIN 
    UPDATE TOUR SET TOUR = v_t, NOMBRE = v_nombre, DURACION = v_dur, DESCRIPCION = v_desc, IMPORTE = v_coste, MAX_PLAZAS = v_max_plazas
  WHERE ID_TOUR = v_idt;
  COMMIT WORK;
END;

/