--Assert Equals
CREATE OR REPLACE FUNCTION ASSERT_EQUALS (salida BOOLEAN, salida_esperada BOOLEAN) RETURN VARCHAR2 AS 
BEGIN
  IF (salida = salida_esperada) THEN
    RETURN 'EXITO';
  ELSE
    RETURN 'FALLO';
  END IF;
END ASSERT_EQUALS;
/

CREATE OR REPLACE FUNCTION COMPUTE_PRICE (p_id_pago PAGO.ID_PAGO%TYPE) RETURN PAGO.IMPORTE%TYPE AS
    sum_res PAGO.IMPORTE%TYPE;
BEGIN
    SELECT SUM(IMPORTE) INTO sum_res FROM (
        SELECT IMPORTE FROM PAGO WHERE ID_PAGO = p_id_pago UNION ALL
        SELECT IMPORTE FROM ENTRADA WHERE ID_PAGO = p_id_pago UNION ALL
        SELECT IMPORTE FROM SEGURO WHERE ID_PAGO = p_id_pago UNION ALL
        SELECT IMPORTE FROM BONUS WHERE ID_PAGO = p_id_pago
    );
    RETURN sum_res * 1.21;
END COMPUTE_PRICE;
/

--BEGIN
--    DBMS_OUTPUT.PUT_LINE(COMPUTE_PRICE(1)); 
--END;